---
- name: Deploy Monitoring Stack
  hosts: monitoring_instance # Doit correspondre Ã  l'inventaire de Malika
  become: yes
  roles:
    - docker      # On installe d'abord Docker
    - monitoring  # Ensuite on lance Prometheus/Grafana